selenium:
  headless: false 
  timeoutSec: 60
  driver:
    path: /Users/antonzhuikov/exchangerates/produce-forex-rate/src/main/resources/drivers/chromedriver_mac
    type: webdriver.chrome.driver
forex:
  user:
    login: ''
    password: ''
produce:
  http:
    is-enabled: false
    URL: http://localhost:9000/strategy/ers
csv:
  is-enabled: true
  file: /Users/antonzhuikov/exchangerates/test.csv
kafka:
  is-enabled: false
spring:
  kafka:
    #    bootstrap-servers: ${kafka_bootstrap_servers:host.minikube.internal:9094}
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: ${random.uuid}
      retries: 2
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "cup:com.wcreators.produceforexrate.dto.CupPointDTO"
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
